/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iTelegramSol from "./ITelegram.sol";
export { Attacker__factory } from "./Attacker__factory";
export { Fallback__factory } from "./Fallback__factory";
export { Telephone__factory } from "./Telephone__factory";
