/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iTelegramSol from "./ITelegram.sol";
export type { iTelegramSol };
export type { Attacker } from "./Attacker";
export type { Fallback } from "./Fallback";
export type { Telephone } from "./Telephone";
export * as factories from "./factories";
export { Attacker__factory } from "./factories/Attacker__factory";
export { Fallback__factory } from "./factories/Fallback__factory";
export type { ITelephone } from "./ITelegram.sol/ITelephone";
export { ITelephone__factory } from "./factories/ITelegram.sol/ITelephone__factory";
export { Telephone__factory } from "./factories/Telephone__factory";
