/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  BytesLike,
  Overrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Vault, VaultInterface } from "../Vault";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_password",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "locked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_password",
        type: "bytes32",
      },
    ],
    name: "unlock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161025238038061025283398181016040528101906100329190610094565b60016000806101000a81548160ff02191690831515021790555080600181905550506100c1565b600080fd5b6000819050919050565b6100718161005e565b811461007c57600080fd5b50565b60008151905061008e81610068565b92915050565b6000602082840312156100aa576100a9610059565b5b60006100b88482850161007f565b91505092915050565b610182806100d06000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063cf3090121461003b578063ec9b5b3a14610059575b600080fd5b610043610075565b60405161005091906100c9565b60405180910390f35b610073600480360381019061006e919061011f565b610086565b005b60008054906101000a900460ff1681565b8060015414156100ab5760008060006101000a81548160ff0219169083151502179055505b50565b60008115159050919050565b6100c3816100ae565b82525050565b60006020820190506100de60008301846100ba565b92915050565b600080fd5b6000819050919050565b6100fc816100e9565b811461010757600080fd5b50565b600081359050610119816100f3565b92915050565b600060208284031215610135576101346100e4565b5b60006101438482850161010a565b9150509291505056fea264697066735822122032f5d990432106246b0440b8b04aa5d88a5f4003d9b1a033ac72ce503507e33a64736f6c63430008090033";

type VaultConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VaultConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Vault__factory extends ContractFactory {
  constructor(...args: VaultConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    _password: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Vault> {
    return super.deploy(_password, overrides || {}) as Promise<Vault>;
  }
  override getDeployTransaction(
    _password: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_password, overrides || {});
  }
  override attach(address: string): Vault {
    return super.attach(address) as Vault;
  }
  override connect(signer: Signer): Vault__factory {
    return super.connect(signer) as Vault__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VaultInterface {
    return new utils.Interface(_abi) as VaultInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Vault {
    return new Contract(address, _abi, signerOrProvider) as Vault;
  }
}
