/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITelephone,
  ITelephoneInterface,
} from "../../ITelegram.sol/ITelephone";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "changeOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITelephone__factory {
  static readonly abi = _abi;
  static createInterface(): ITelephoneInterface {
    return new utils.Interface(_abi) as ITelephoneInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITelephone {
    return new Contract(address, _abi, signerOrProvider) as ITelephone;
  }
}
