/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Delegate__factory } from "./Delegate__factory";
export { Delegation__factory } from "./Delegation__factory";
